### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by PieterSlangen** [kevinruscoe/acf-star-rating#21]
After activating it, I got this error:

Parse error: syntax error, unexpected 'Clear' (T_STRING) in /home/fluxdemo/public_html/demo/demo32/wp-content/plugins/acf-star-rating-master/acf-star_rating-v5.php on line 132

**Comment by geckoseo** [comment]
> After activating it, I got this error:
> 
> Parse error: syntax error, unexpected 'Clear' (T_STRING) in /home/fluxdemo/public_html/demo/demo32/wp-content/plugins/acf-star-rating-master/acf-star_rating-v5.php on line 132

Same here, the problem is the code is not properly enclosed. This fixes it:

`<a href=\"#clear-stars" class="button button-small clear-button">'.__('Clear','acf-star_rating').'</a>`

There are other problems too.. mixed quotes in the js files, closing php tags in the files with whitespace after them, the tiny plugin is loading the entire FA4 library into the backend.

The utility of the plugin is nice, but I think needs a bit of work to clean it up and maybe get checked by someone with the skill to recognise any potential vulnerabilities. Unfortunately I wouldn't know for sure at my level otherwise I would clean it up and submit a PR, but there is something in the syntax here which makes me tingle a bit so I'm going to look for an alternative.

**Comment by kevdotbadger** [comment]
Fancy making a PR for this?

**Comment by kevdotbadger** [comment]
Yeah, looks like a recent PR bust this. Should be fine now.
